### PR TITLE
Add an option to submit an url for bulk uploads (manually processed by admins later)

### PR DESCRIPTION
**Pull request by C4ptainCrunch**
IF this gains traction, we can then see what platform is used most and see if we can automate some parts of the work (https://xkcd.com/1205/)
And if it does, it will mean this feature is a big win :) (most probably it won't be and it won't create much manual work for us)

image

image

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
up

**Review by Bruno-brsy — COMMENTED** [review]
So, from what I understand, it stores the bulk document somewhere, but we need to put ourselves in the DB? Or it will do automatically?
Should we explain a little bit better which format the user should use?
image
We must use something like `info-f106`, I suppose. But, can we use `info 106`? (I suppose, no), or `Projet d'informatique 1`, But most people will just put something like `Projet`, how can we differentiate all the courses with `project` in the name, we should put some guideline for naming the directories.

**Comment by C4ptainCrunch** [comment]
> So, from what I understand, it stores the bulk document somewhere, but we need to put ourselves in the DB?

Yes, we need to import it by hand. Why ? Because we don't even know if people are going to use the feature so why bother implementing an auto import if it's not used ? And if it is, should we be able to import zips over http ? wetransfer ? google drive ? dropbox ? Let's wait to see what arrives in our hands and if the workload becomes too big: 1) we will have succeeded as we will have loads of documents 2) it will be time to automate it then

> Should we explain a little bit better which format the user should use?

I'm explicitly vague as it's a human that will process the files. We can handle almost any format. In this way, we add as little friction as possible. And if it's too vague and hard to work with ? We can still send an email to the user and ask for more info. We will still have won as now, we have the contact of a motivated user that is keen to help us upload a lot of files.

**Comment by C4ptainCrunch** [comment]
I would even say that if a user submits an url that does gives a 404 we can already be happy as now we know that that user if motivated to help and we can then contact them :)

**Comment by Bruno-brsy** [comment]
> Yes, we need to import it by hand.

I prefer too, for the same reason as you.

> I'm explicitly vague as it's a human that will process the files.
Yeah, ok, perfect.

**Review by Bruno-brsy — APPROVED** [review]

**Review by etnarek — APPROVED** [review]
Could be interesting to notify the admin somehow when a new document is available in the long term 
But it can be added in a later pr

**Comment by Mortinat** [comment]
I don't know how much is doable but we could accept direct upload of zip but with a sanitizing of the zip file. Would allow to see if the zip have the required element etc

**Review by Mortinat — APPROVED** [review]

**Pull request merged**
