### PR TITLE
Replacing all the print calls by calls to log

### PR DESCRIPTION
**Pull request by amrutha1098**
#267 replacing all the print calls by calls to log

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
Hello again !

The tests are failing because of [Black](https://github.com/psf/black) and [isort](https://github.com/PyCQA/isort) are failing.
Could you install pre-commit (`pip install pre-commit`) and then run it locally ? (`pre-commit run --all`) so that it reformats your files and then commit the changes ? 
Sorry about those convoluted steps, we should have documented them in the README.

Once that is done, the tests will be able to run and we can review your PR :)

**Comment by amrutha1098** [comment]
Hi @C4ptainCrunch , I have pushed the changes from pre-commit present in MR https://github.com/UrLab/DocHub/issues/267 .
Please let me know if any other changes are required.
Thanks!

**Review by C4ptainCrunch — CHANGES_REQUESTED** [review]
Hi, 

I did checkout your PR and tried running `./manage.py runserver` but it does not show the warning (`you are running Dochub with DEBUG=True`) that comes from https://github.com/UrLab/DocHub/pull/272/files#diff-a319b4e09ca929987f4eadd50f04ac0d0afeebd4ade69e396ffd43fd557baa47L213 but when checkouting `main`, it does. So it seems your change from `print` to `logging.debug` breaks the output. I'm guessing it's due to the logging configuration but i'm not sure. 

Could you try to fix this and ensure that the `print` your replaced still output text in the terminal ? Thank you !

**Comment by amrutha1098** [comment]
Hi @C4ptainCrunch , I have made few changes for logging the statements .

Now all debug logs are shown in stdout / terminal.
I have created a file [www/logger_settings.py](https://github.com/UrLab/DocHub/pull/272/files#diff-ccf9cbc322b5046510758e16270fcbf7252baa500a6dff21d8f05b75d3a0c9f0) in which we can specify the log level we want to show in stdout. 

Please review and let me know if any other changes are required . 
Thank you.

**Comment by C4ptainCrunch** [comment]
Hi @amrutha1098 !
Did you have some time to look at the logging system of Django like suggested by @Mortinat ? Are you still interested in working on this PR ?

**Comment by amrutha1098** [comment]
Hi @C4ptainCrunch , currently held up in other work so i am not able to work on this.

**Comment by C4ptainCrunch** [comment]
Thank you for letting us know :) I'm closing the PR to clean up a bit the repo, but if you still have time later, feel free to reopen !

**Pull request closed without merging**
